# Generated by Django 5.2.9 on 2026-01-29 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants_users',
            field=models.ManyToManyField(blank=True, related_name='events_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
