# Generated by Django 5.2.9 on 2025-12-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
