# Generated by Django 5.2.9 on 2025-12-31 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participant_is_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants_users',
            field=models.ManyToManyField(blank=True, related_name='events_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
