# Generated by Django 5.2.9 on 2025-12-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_participants_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to='tasks_asset'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
