# Generated by Django 5.2.9 on 2025-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_asset_delete_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to='events_asset'),
        ),
    ]
