# Generated by Django 5.2.9 on 2025-12-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='default_img.jpg', null=True, upload_to='events_asset'),
        ),
    ]
