# Generated by Django 5.2.9 on 2025-12-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
